import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Aroglin Spice Farms",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center p-4">
          <Image src="/logo.jpg" alt="Aroglin Spice Farms Logo" width={50} height={50} />
          <h1 className="ml-4 text-2xl font-bold">Aroglin Spice Farms</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
